{% set name = "drf-api-tracking" %}
{% set version = "1.8.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/drf-api-tracking-{{ version }}.tar.gz
  sha256: 99a2b2ee6fa30a9b0765cd5d8baed009b2129c8d1403865dbbaf203124be9353

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - django >=1.7
    - djangorestframework >=3
    - python >=3.6
    - pytz

test:
  imports:
    - rest_framework_tracking
    - rest_framework_tracking.migrations
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lingster/drf-api-tracking
  summary: Utils to log Django Rest Framework requests to the database
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichelML
